### ISSUE TITLE
Support an option to ignore tests for specific orientation

### ISSUE THREAD

**Issue by glad-shopify** [Shopify/android-testify#183]
Screenshots that request orientation change - through `rule.setOrientation(orientation)` - are sometimes flaky and sometimes result in `UnexpectedOrientationException` causing the test to fail.  When this happens it's common to (manually) force the test to run again from CI.

This feedback relates to:
- [x] The Kotlin library
- [ ] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**Describe the solution you'd like**

One possible solution is to run the test on devices explicitly set to the two orientations (without the need to call `setOrientation` in code).

Then in the tests itself, to ignore for certain orientation, one can specify so in the `ScreenshotInstrumentation` annotation.

For example:

```
class ScreenshotInstrumentationOrientationTest {

    @get:Rule
    val rule: ScreenshotRule<TestActivity> = ScreenshotRule(TestActivity::class.java)

    @ScreenshotInstrumentation(orientationToIgnore = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)
    @Test
    fun testLandscapeOnly() {
        rule.assertSame()
    }
}
```

In the above, the expected result would be a screenshot produced on a Landscape device but not produced on Portrait.

**Describe alternatives you've considered**

One quick and easy solution to getting around setting the orientation in code, is to run the tests on two separate devices; one on Portrait and another on Landscape.

The issue with doing this is (with the current library) is that two screenshots would be produced for the respective orientations.

**Comment by glad-shopify** [comment]
I contemplated if this feature/code would read better under a more positive tone (i.e. `orientationToRecord`) rather than a negative one (i.e. `orientationToIgnore`).

For example: 
```
class ScreenshotInstrumentationOrientationTest {

    @get:Rule
    val rule: ScreenshotRule<TestActivity> = ScreenshotRule(TestActivity::class.java)

    @ScreenshotInstrumentation(orientationToRecord = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE)
    @Test
    fun testLandscapeOnly() {
        rule.assertSame()
        if (rule.deviceOrientation == ActivityInfo.SCREEN_ORIENTATION_PORTRAIT) {
            assertFalse(rule.outputFileExists)
        }
    }
}
```

Thoughts @DanielJette ?

**Comment by DanielJette** [comment]
I suppose it depends on what you'd expect the default to be. It's a bit tough because the emulator can be configured to any orientation you want and that's outside the control of Testify. I can see this making sense either way though. I think the default would be to record "all orientations" and so do you want to specify `All minus the specified` or `None, just these`.
The current behaviour is "all", so `all minus the specified` is probably the least disruptive option
