### ISSUE TITLE
Update docs to show how to override inferred config

### ISSUE THREAD

**Issue by ryansama** [Shopify/android-testify#271]
**Is your feature request related to a problem? Please describe.**
Currently it is not clear how to override the inferred `testify` configurations -- after realizing that the config is wrong using `./gradlew testifySettings`, I had to dig through releases to find out how to override them and finally came across a note [here](https://github.com/Shopify/android-testify/releases/tag/1.1.0-beta3). 

Specifying how to override the configs using `testify { ...` in `build.gradle` would save some headaches :) 

This feedback relates to:
- [x] The Kotlin library
- [x] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [x] The documentation

**Describe the solution you'd like**
Just some notes in the README describing how to override the settings.

**Describe alternatives you've considered**
Other alternatives could be to improve error messaging to hint that maybe the inferred config is wrong, and how you can override them as a hint.

**Additional context**
N/A

**Comment by DanielJette** [comment]
Moved to https://github.com/ndtp/android-testify/issues/89
