### ISSUE TITLE
Update docs/sample to include how to run in non-app modules (e.g. Android library module)

### ISSUE THREAD

**Issue by ryansama** [Shopify/android-testify#272]
**Is your feature request related to a problem? Please describe.**
I'd like to know how to get the tests working in a non-app module such as an Android library module. Would be fantastic if the docs mentioned how to do this, and even better some sample code to demonstrate it.

This feedback relates to:
- [x] The Kotlin library
- [x] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [x] The sample code
- [x] The documentation

**Describe the solution you'd like**
As mentioned above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DanielJette** [comment]
Hi @ryansama
Thanks for the feedback! I have plans to create full documentation on how to use Testify with an Android Library module project. Those documents aren't quite ready yet, but I do have a work-in-project branch where I had added a library module to the Sample app. I just opened that as a draft that you can take a look at here https://github.com/Shopify/android-testify/pull/273

Most likely, you'll want to look at the gradle configuration here:

https://github.com/Shopify/android-testify/pull/273/files#diff-7be9b607348050f71804f7ca41acb93b9b6434014f095c19f3264d2127b87c14R53-R56

**Comment by ryansama** [comment]
That seemed to work very well, it wasn't too clear what exactly I should name the application/package, thank you!

**Comment by DanielJette** [comment]
Moved to https://github.com/ndtp/android-testify/issues/90
